const searchData = [
  {
    link: '/phc/welcome',
    content: 'Welcome to The Personalised Healthcare Systems Map The complexity of Personalised '
      + 'Healthcare (PHC) calls for us to be systems thinkers with the ability '
      + 'to think and act from a whole system perspective and make decisions in light of the long-term health '
      + 'of the whole system. This map will provide a broad picture view and exploration of components of the '
      + 'PHC ecosystem, the interconnectedness of the system at play, and how you can engage with PHC. Personalised '
      + 'Healthcare at Roche Before diving into the PHC systems map, learn about why PHC is important and '
      + 'Roche’s PHC vision and strategy on the PHC portal. How we built the PHC Systems Map '
      + 'This site is built around the future patient journey that is fully personalized. '
      + 'It includes key PHC concepts that are relevant for each step of a patient’ care as well as'
      + ' key system enablers that are important to keep in mind. Check out the video below to learn '
      + 'about how we envision the future patient journey to be different from the existing one and how '
      + 'we built the PHC systems map.',
  },
  {
    link: '/phc/future-patient-journey/diagnosis/overview',
    content: 'The goal of early and personalized diagnosis is to reduce and eventually '
      + 'eliminate misdiagnosis and delayed diagnosis. Clinicians in partnership with '
      + 'patients are able to select the most appropriate (based on disease presentation '
      + 'and activity) and complete diagnostic work-up leveraging diagnostic guidance tools. The '
      + 'right diagnostic tools are easily available and reimbursed quickly to ensure timely testing. '
      + 'This includes the use of: '
      + 'Existing and newer “omics” tools in oncology '
      + 'Emerging digital technologies in other diseases '
      + 'An earlier diagnosis to catch disease when it is more treatable or curable.',
  },
  {
    link: '/phc/future-patient-journey/access/overview',
    content: 'With rapid access to personalized interventions, patients and healthcare providers have access '
      + 'to the treatment options as recommended in the personalised care plan. Markets no longer feel compelled to '
      + 'add hurdles to limit the prescription of high-cost therapeutics because of novel, '
      + 'data-enabled payment models. '
      + 'Payers recognise the value driven by the intervention due to the increasing '
      + 'application of full outcomes-based and value-based access models.',
  },
  {
    link: '/phc/future-patient-journey/care/overview',
    content: '“[The average oncologist] would have to read 29 hours each work day to stay abreast of new insights…” '
      + '- ASCO 2018 Individual treatment selection becomes more challenging as the volume, variety, and '
      + 'depth of health data increases and advances in diagnostics and imaging provide deeper insights '
      + 'into patients and their disease. Clinical Decision Support (CDS) systems empower the healthcare provider '
      + '(HCP) and patient to make an informed and confident decision Clinical Decision Support (CDS) '
      + 'systems empower the healthcare provider (HCP) and patient to make an informed and confident decision '
      + 'An integrated and customized view of a patient’s clinical profile (including for tumor boards) '
      + ' Guideline and pathway recommendations, '
      + 'Relevant clinical trials and publications, '
      + 'Relevant coverage and reimbursement information. '
      + 'Moreover, CDS Systems are increasingly evolving to provide information on pools of relevant'
      + ' patients with similar profiles, their treatment plan and outcomes. Artificial Intelligence '
      + 'and Machine Learning tools can further assist the HCP inselecting personalized care plans '
      + 'through CDS systems as the volume and quality of real-world data (RWD) increases.',
  },
  {
    link: '/phc/future-patient-journey/monitoring/overview',
    content: 'Patients are effectively triaged and managed in a more efficient and timely manner through '
      + 'the application of data-driven early and continuous monitoring outside of the specialist’s office. '
      + 'Assess patient function and disease progression Measure response to treatment Optimize adverse event '
      + 'management to trigger earlier intervention when meaningful change occurs This minimises patient burden '
      + 'and cost of ongoing treatment, and optimises outcomes through timelier intervention.',
  },
  {
    link: '/phc/future-patient-journey/data/overview',
    content: 'A free flow of linked, longitudinal patient data between healthcare providers all '
      + 'throughout a patient\'s care is a prerequisite for personalised healthcare (PHC). '
      + 'This flow of information allows a patient to move seamlessly between providers. Data allows the '
      + 'system to measure the impact of each component of the health system, thus driving continuous '
      + 'efficiency improvements.Data is also collected and used to support and measure the impact of '
      + 'various interventions across the health system driving access and funding. Large, high-quality '
      + 'aggregated data sets are made available in select cases and areused to support advanced tools, '
      + 'such as Clinical Decision Support (CDS) systems, and research and development, both within '
      + 'academia and commercial businesses. Data sharing not only optimises outcomes for individual '
      + 'patients but is also used to deliver new insights to all those patients with a similar '
      + 'profile and to the wider health system.',
  },
  {
    link: '/phc/future-patient-journey/data/real-world-data',
    content: 'Description '
      + 'Real-World Data (RWD) is defined as data relating to patient health routinely collected from a variety of '
      + 'sources outside of traditional controlled clinical interventional trials, under real-life clinical practice. '
      + 'The evidence derived from the analysis and/or synthesis of RWD is called Real-World Evidence (RWE).'
      + ' RWD can be collected from various sources such as electronic/medical health records, Digital Health '
      + 'solutions, pharmacy claims, insurance claims, disease and product registries, diagnostics/omics'
      + ' databases, hospitals/outpatient visits, health surveys and patient-reported outcomes (PROs),'
      + ' non-investigational studies, social media, etc.'
      + 'Why it is important for PHC '
      + 'Bridge evidence gaps of randomized control trials (RCTs)- The discovery of smaller and smaller '
      + 'patient sub-populations (e.g., rare cancer-driving genomic alterations) is making it unfeasible '
      + 'to run RCTs. Supplementary data sources, such as RWD, are needed to understand patient characteristics and'
      + ' treatment effectiveness. The heterogeneity of patient populations means that RCT data have low '
      + 'generalizability. This also leads to evidence gaps in treatments and patient outcomes in the real-world '
      + 'setting. However, RWD provides a much larger and more heterogeneous patient pool. RCTs are costly '
      + 'and time-consuming as compared to RWD.'
      + ' Smarter & more efficient R&D – Insights from RWD can provide learnings, '
      + 'such as treatment decisions in the real-world setting and molecularly-guided '
      + 'treatment options (MGTO). This can potentially fuel new research questions '
      + 'that can lead to smarter and more efficient R&D. '
      + 'RWD is a key component of our PHC vision and strategy because: '
      + 'RWD is a source of Meaningful Data at Scale (MDAS). MDAS combines high quality, high volume of data per '
      + 'patient with the number of patients covered. In other words, MDAS is comprised of deep, longitudinal '
      + 'data from broad patient populations. '
      + "RWD fuels the PHC engine with continuous learning from every patient's "
      + 'experience to create both a high-resolution view of each patient and treatments '
      + "personalized to each patient's needs. "
      + 'Downstream use of RWE in regulatory / Health Technology Assessment (HTA) / payer '
      + 'decision-making can also facilitate and support the approvals of novel PHC solutions. '
      + 'What Roche is doing in this area '
      + 'Roche’s RWD assets span sources including platforms, registries, and genomic databases. Roche is using RWD to '
      + 'advance Research, Regulatory, Access, Medical and Commercial objectives. '
      + 'Key considerations of using RWD '
      + 'Harmonizing data from multiple sources while retaining data comprehensiveness '
      + 'Ensuring similar data quality and compatibility '
      + 'Extracting meaningful information from unstructured data (e.g., physician notes or genomic testing reports) '
      + 'Validating RWD endpoints '
      + 'Identifying and accounting for biases '
      + 'Guaranteeing consent, patient privacy and confidentiality '
      + 'Securing needed resources for planning, educating, collecting / upkeeping data, quality control, etc. '
      + 'Taking into consideration the lack of sources of high-quality RWD in ex-US markets '
      + 'Taking into consideration that the market for structured / curated data is nascent '
      + 'Taking into consideration the possibility of immature consensus of defining regulatory-grade '
      + 'RWD and levels of quality that are fit-for-purpose',
  },
  {
    link: '/phc/future-patient-journey/access/cds-systems',
    content: 'Description '
      + 'Increased volumes of healthcare data are now available to both HCPs and patients. '
      + 'This overwhelming growth in healthcare data is making clinical decisions more complex. '
      + 'High-quality Clinical Decision Support (CDS) leverages objective health data and analytics '
      + 'to improve individual patient outcomes by enabling more confident clinical decisions in '
      + 'real time at the point of care. Most CDS solution are currently in Oncology, followed by '
      + 'Neuroscience and Ophthalmology—all areas of interest for Roche. Most CDS solutions are '
      + 'currently in Oncology, followed by Neuroscience and Ophthalmology—all areas of interest '
      + 'for Roche. For more information, please visit our CDS systems module. In the future, we '
      + 'can imagine having patient interface in CDS systems and dedicated patient decision support '
      + 'tools to help patients actively participate and their care plan. Why it is important for PHC '
      + 'Improved access & personalized care '
      + 'CDS systems have the potential to improve both healthcare '
      + 'provider and patient experiences as well as to enable a shared '
      + 'decision making between HCPs and their patients. High quality CDS systems '
      + 'should also act as Patient Decision Support by providing relevant information '
      + 'and including a patient interface. CDS systems will also impact pharmaceutical industries by '
      + 'influencing how products are represented at the time of clinical decision making. Click button below to see: '
      + 'What Roche is doing in this area '
      + 'At Roche Pharma, our vision is that high-quality CDS systems improve individual patient outcomes '
      + 'by supporting personalized clinical decisions in the clinical setting. '
      + 'At Roche Pharma, our vision is that high-quality CDS systems improve individual patient outcomes '
      + 'by supporting personalized clinical decisions in the clinical setting. 1. CDS systems are of high quality. '
      + '2. We are prepared to operate in an environment where CDS has significant influence on clinical care. '
      + 'However, in order to maintain our objectivity and credibility, Roche Pharma is not independently developing '
      + 'or commercializing CDS systems. Roche Diagnostics is further developing the CDS system NAVIFY. '
      + 'The NAVIFY Decision Support Portfolio consists of a cross-diagnostics platform that hosts an '
      + 'ecosystems of workflow products, apps and services. It is comprised of: '
      + 'NAVIFY Tumor Board, a could-based software solution that streamlines and standardizes preparation, '
      + 'facilitation and documentation of oncology treatment decisions; oncology care teams can more easily '
      + 'upload patient records from all diagnostic disciplines to one dashboard. Having complete patient '
      + 'diagnostic information in one location helps experts review all relevant files quickly and align on '
      + 'the best possible treatment plan for each patients NAVIFY Clinical Trial Match andNAVIFY Publication Search '
      + 'make it easier to pull relevant reference information from global databases. '
      + 'Key drivers/considerations '
      + 'High-quality CDS: The impact of CDS on patients, healthcare '
      + 'providers and the business is dependent on the quality of CDS. '
      + 'Objectivity is essential to preserve the integrity of CDS systems and pharmaceutical credibility.',
  },
  {
    link: '/phc/future-patient-journey/care/cds-systems',
    content: 'Description '
      + 'Increased volumes of healthcare data are now available to both HCPs and patients. '
      + 'This overwhelming growth in healthcare data is making clinical decisions more complex. '
      + 'High-quality Clinical Decision Support (CDS) leverages objective health data and analytics '
      + 'to improve individual patient outcomes by enabling more confident clinical decisions in '
      + 'real time at the point of care. Most CDS solution are currently in Oncology, followed by '
      + 'Neuroscience and Ophthalmology—all areas of interest for Roche. Most CDS solutions are '
      + 'currently in Oncology, followed by Neuroscience and Ophthalmology—all areas of interest '
      + 'for Roche. For more information, please visit our CDS systems module. In the future, we '
      + 'can imagine having patient interface in CDS systems and dedicated patient decision support '
      + 'tools to help patients actively participate and their care plan. Why it is important for PHC '
      + 'Improved access & personalized care '
      + 'CDS systems have the potential to improve both healthcare '
      + 'provider and patient experiences as well as to enable a shared '
      + 'decision making between HCPs and their patients. High quality CDS systems '
      + 'should also act as Patient Decision Support by providing relevant information '
      + 'and including a patient interface. CDS systems will also impact pharmaceutical industries by '
      + 'influencing how products are represented at the time of clinical decision making. Click button below to see: '
      + 'What Roche is doing in this area '
      + 'At Roche Pharma, our vision is that high-quality CDS systems improve individual patient outcomes '
      + 'by supporting personalized clinical decisions in the clinical setting. '
      + 'At Roche Pharma, our vision is that high-quality CDS systems improve individual patient outcomes '
      + 'by supporting personalized clinical decisions in the clinical setting. 1. CDS systems are of high quality. '
      + '2. We are prepared to operate in an environment where CDS has significant influence on clinical care. '
      + 'However, in order to maintain our objectivity and credibility, Roche Pharma is not independently developing '
      + 'or commercializing CDS systems. Roche Diagnostics is further developing the CDS system NAVIFY. '
      + 'The NAVIFY Decision Support Portfolio consists of a cross-diagnostics platform that hosts an '
      + 'ecosystems of workflow products, apps and services. It is comprised of: '
      + 'NAVIFY Tumor Board, a could-based software solution that streamlines and standardizes preparation, '
      + 'facilitation and documentation of oncology treatment decisions; oncology care teams can more easily '
      + 'upload patient records from all diagnostic disciplines to one dashboard. Having complete patient '
      + 'diagnostic information in one location helps experts review all relevant files quickly and align on '
      + 'the best possible treatment plan for each patients NAVIFY Clinical Trial Match andNAVIFY Publication Search '
      + 'make it easier to pull relevant reference information from global databases. '
      + 'Key drivers/considerations '
      + 'High-quality CDS: The impact of CDS on patients, healthcare '
      + 'providers and the business is dependent on the quality of CDS. '
      + 'Objectivity is essential to preserve the integrity of CDS systems and pharmaceutical credibility.',
  },
  {
    link: '/phc/future-patient-journey/monitoring/cds-systems',
    content: 'Description '
      + 'Increased volumes of healthcare data are now available to both HCPs and patients. '
      + 'This overwhelming growth in healthcare data is making clinical decisions more complex. '
      + 'High-quality Clinical Decision Support (CDS) leverages objective health data and analytics '
      + 'to improve individual patient outcomes by enabling more confident clinical decisions in '
      + 'real time at the point of care. Most CDS solution are currently in Oncology, followed by '
      + 'Neuroscience and Ophthalmology—all areas of interest for Roche. Most CDS solutions are '
      + 'currently in Oncology, followed by Neuroscience and Ophthalmology—all areas of interest '
      + 'for Roche. For more information, please visit our CDS systems module. In the future, we '
      + 'can imagine having patient interface in CDS systems and dedicated patient decision support '
      + 'tools to help patients actively participate and their care plan. Why it is important for PHC '
      + 'Improved access & personalized care '
      + 'CDS systems have the potential to improve both healthcare '
      + 'provider and patient experiences as well as to enable a shared '
      + 'decision making between HCPs and their patients. High quality CDS systems '
      + 'should also act as Patient Decision Support by providing relevant information '
      + 'and including a patient interface. CDS systems will also impact pharmaceutical industries by '
      + 'influencing how products are represented at the time of clinical decision making. Click button below to see: '
      + 'What Roche is doing in this area '
      + 'At Roche Pharma, our vision is that high-quality CDS systems improve individual patient outcomes '
      + 'by supporting personalized clinical decisions in the clinical setting. '
      + 'At Roche Pharma, our vision is that high-quality CDS systems improve individual patient outcomes '
      + 'by supporting personalized clinical decisions in the clinical setting. 1. CDS systems are of high quality. '
      + '2. We are prepared to operate in an environment where CDS has significant influence on clinical care. '
      + 'However, in order to maintain our objectivity and credibility, Roche Pharma is not independently developing '
      + 'or commercializing CDS systems. Roche Diagnostics is further developing the CDS system NAVIFY. '
      + 'The NAVIFY Decision Support Portfolio consists of a cross-diagnostics platform that hosts an '
      + 'ecosystems of workflow products, apps and services. It is comprised of: '
      + 'NAVIFY Tumor Board, a could-based software solution that streamlines and standardizes preparation, '
      + 'facilitation and documentation of oncology treatment decisions; oncology care teams can more easily '
      + 'upload patient records from all diagnostic disciplines to one dashboard. Having complete patient '
      + 'diagnostic information in one location helps experts review all relevant files quickly and align on '
      + 'the best possible treatment plan for each patients NAVIFY Clinical Trial Match andNAVIFY Publication Search '
      + 'make it easier to pull relevant reference information from global databases. '
      + 'Key drivers/considerations '
      + 'High-quality CDS: The impact of CDS on patients, healthcare '
      + 'providers and the business is dependent on the quality of CDS. '
      + 'Objectivity is essential to preserve the integrity of CDS systems and pharmaceutical credibility.',
  },
  {
    link: '/phc/future-patient-journey/diagnosis/cds-systems',
    content: 'Description '
      + 'Increased volumes of healthcare data are now available to both HCPs and patients. '
      + 'This overwhelming growth in healthcare data is making clinical decisions more complex. '
      + 'High-quality Clinical Decision Support (CDS) leverages objective health data and analytics '
      + 'to improve individual patient outcomes by enabling more confident clinical decisions in '
      + 'real time at the point of care. Most CDS solution are currently in Oncology, followed by '
      + 'Neuroscience and Ophthalmology—all areas of interest for Roche. Most CDS solutions are '
      + 'currently in Oncology, followed by Neuroscience and Ophthalmology—all areas of interest '
      + 'for Roche. For more information, please visit our CDS systems module. In the future, we '
      + 'can imagine having patient interface in CDS systems and dedicated patient decision support '
      + 'tools to help patients actively participate and their care plan. Why it is important for PHC '
      + 'Improved access & personalized care '
      + 'CDS systems have the potential to improve both healthcare '
      + 'provider and patient experiences as well as to enable a shared '
      + 'decision making between HCPs and their patients. High quality CDS systems '
      + 'should also act as Patient Decision Support by providing relevant information '
      + 'and including a patient interface. CDS systems will also impact pharmaceutical industries by '
      + 'influencing how products are represented at the time of clinical decision making. Click button below to see: '
      + 'What Roche is doing in this area '
      + 'At Roche Pharma, our vision is that high-quality CDS systems improve individual patient outcomes '
      + 'by supporting personalized clinical decisions in the clinical setting. '
      + 'At Roche Pharma, our vision is that high-quality CDS systems improve individual patient outcomes '
      + 'by supporting personalized clinical decisions in the clinical setting. 1. CDS systems are of high quality. '
      + '2. We are prepared to operate in an environment where CDS has significant influence on clinical care. '
      + 'However, in order to maintain our objectivity and credibility, Roche Pharma is not independently developing '
      + 'or commercializing CDS systems. Roche Diagnostics is further developing the CDS system NAVIFY. '
      + 'The NAVIFY Decision Support Portfolio consists of a cross-diagnostics platform that hosts an '
      + 'ecosystems of workflow products, apps and services. It is comprised of: '
      + 'NAVIFY Tumor Board, a could-based software solution that streamlines and standardizes preparation, '
      + 'facilitation and documentation of oncology treatment decisions; oncology care teams can more easily '
      + 'upload patient records from all diagnostic disciplines to one dashboard. Having complete patient '
      + 'diagnostic information in one location helps experts review all relevant files quickly and align on '
      + 'the best possible treatment plan for each patients NAVIFY Clinical Trial Match andNAVIFY Publication Search '
      + 'make it easier to pull relevant reference information from global databases. '
      + 'Key drivers/considerations '
      + 'High-quality CDS: The impact of CDS on patients, healthcare '
      + 'providers and the business is dependent on the quality of CDS. '
      + 'Objectivity is essential to preserve the integrity of CDS systems and pharmaceutical credibility.',
  },
];

export default searchData;
